-- Criado em 23/07/2026
-- Gera a quantidade de execuções de todos os relatórios/serviços de Declaração de Matrícula

SELECT  IDREL, 
        SUBSTRING(DESCRELAT,1,PATINDEX('%-%',DESCRELAT)-1) AS CODIGO,
        REPLACE(REPLACE(SUBSTRING(DESCRELAT,PATINDEX('%-%',DESCRELAT)+2,LEN(DESCRELAT) ),'.PDF',''),'.NONE','') AS NOME,
        YEAR(RECCREATEDON) ANO, 
        MONTH(RECCREATEDON) MES, 
        COUNT(*) AS QTD_GERACAO
FROM GRELBATCH
WHERE CODCOLIGADA = 1
AND CODSISTEMA = 'S'
/*
AND IDREL IN (  1177,1511,1127,
                1552,1558,1573,
                1491,1845,1614,
                814,1057,2090,
                1138)
AND YEAR(RECCREATEDON) = 2026
--AND DESCRELAT like '%DECLARAÇÃO DE MATRÍCULA%'
--and DESCRELAT like '%STRICTU%'
--AND MONTH(RECCREATEDON) = 7  
*/
GROUP BY    IDREL, 
            SUBSTRING(DESCRELAT,1,PATINDEX('%-%',DESCRELAT)-1),
            REPLACE(REPLACE(SUBSTRING(DESCRELAT,PATINDEX('%-%',DESCRELAT)+2,LEN(DESCRELAT) ),'.PDF',''),'.NONE',''),
            YEAR(RECCREATEDON), 
            MONTH(RECCREATEDON)
ORDER BY    SUBSTRING(DESCRELAT,1,PATINDEX('%-%',DESCRELAT)-1),
            REPLACE(REPLACE(SUBSTRING(DESCRELAT,PATINDEX('%-%',DESCRELAT)+2,LEN(DESCRELAT) ),'.PDF',''),'.NONE',''),
            YEAR(RECCREATEDON), 
            MONTH(RECCREATEDON) 



-- Query base
SELECT DESCRELAT, YEAR(RECCREATEDON) ANO, MONTH(RECCREATEDON) MES, COUNT(*)
FROM GRELBATCH
WHERE CODCOLIGADA = 1
AND CODSISTEMA = 'S'
AND IDREL IN (1511,1552)
--AND RECCREATEDBY = '10741479'
GROUP BY YEAR(RECCREATEDON), MONTH(RECCREATEDON), DESCRELAT
ORDER BY DESCRELAT, YEAR(RECCREATEDON), MONTH(RECCREATEDON)
