/*REPLICADA E ANALISADA POR LUIS OLIVEIRA PVT SOFTWARE EM 16/02/2021*/
/*ANALISADA POR JEFFERSON FRANCO PVT SOFTWARE EM 18/03/2021*/
/*MODIFICADA POR CLAUDIO PEREIRA - GERTI EM 31/07/2024*/
/*MODIFICADA POR CLAUDIO PEREIRA - GERTI EM 29/08/2024 - S240829-0081 */
/*MODIFICADA POR CLAUDIO PEREIRA - GERTI EM 17/12/2024 - S241112-0057 */

SELECT DISTINCT HTIPOATENDIMENTO.NOME             [TIPO ATENDIMENTO],
                GCOLIGADA.NOME                    [NOME COLIGADA],
                SCONTRATO.CODFILIAL               [FILIAL],
                GCOLIGADA.NOMEFANTASIA            [NOME FANTASIA COLIGADA],
                HATENDIMENTOEXT.CODATENDIMENTO,
                HATENDIMENTOEXT.CODSTATUS,
                CASE HATENDIMENTOEXT.CODSTATUS
                  WHEN 'A' THEN 'Em andamento'
                  WHEN 'R' THEN 'Concluído a responder'
                  WHEN 'O' THEN 'Concluído respondido'
                  WHEN 'F' THEN 'Concluído confirmado'
                  WHEN 'U' THEN 'Concluído automático(pelo sistema)'
                  WHEN 'V' THEN 'Avaliado'
                  WHEN 'G' THEN 'Agendado a responder'
                  WHEN 'E' THEN 'Agendado respondido'
                  WHEN 'T' THEN 'Aguardando terceiros'
                  WHEN 'C' THEN 'Cancelado'
                  WHEN 'D' THEN 'Despertado'
                  ELSE HATENDIMENTOEXT.CODSTATUS
                END                               [STATUS],
                HATENDIMENTOEXT.CODTIPOATENDIMENTO,
                HATENDIMENTOEXT.CODTAREFA,
                HATENDIMENTOEXT.CODLOCAL,
                HATENDIMENTOEXT.ABERTURA,
                HATENDIMENTOEXT.DATAULTIMOREPASSE [DATA ÚLTIMO REPASSE],
                HATENDIMENTOBASE.RECMODIFIEDON    [DATA DA ÚLTIMA ATUALIZAÇÃO],
                HATENDIMENTOEXT.RAALUNO,
                HATENDIMENTOEXT.NOME              [NOME NO ATENDIMENTO],
                HATENDIMENTOEXT.CODATENDENTE,
                HATENDIMENTOEXT.CODATENDENTERESP,
                HTAREFA.NOME                      [TAREFA],
                PP2.NOME                          [ANTEDENTE],
                PP3.NOME                          [ANTEDENTE RESPONSAVEL],
                SHABILITACAOFILIAL.CODCURSO,
                SCURSO.NOME                       [CURSO],
                SCURSO.CODCURSO,
                SCURSO.CODESCOLA,
                1                                 AS QTD,
                HCLIENTEATENDIMENTO.CODCOLIGADA,
                SPLETIVO.IDPERLET,
                SPLETIVO.CODPERLET,
                STIPOCURSO.NOME                   [NIVEL_ENSINO]
FROM   HATENDIMENTOEXT (NOLOCK)
       INNER JOIN HATENDIMENTOBASE (NOLOCK)
               ON HATENDIMENTOEXT.CODCOLIGADA = HATENDIMENTOBASE.CODCOLIGADA
                  AND HATENDIMENTOEXT.CODATENDIMENTO = HATENDIMENTOBASE.CODATENDIMENTO
       INNER JOIN HCLIENTEATENDIMENTO (NOLOCK)
               ON HCLIENTEATENDIMENTO.CODATENDIMENTO = HATENDIMENTOEXT.CODATENDIMENTO
                  AND HCLIENTEATENDIMENTO.CODCOLIGADA = HATENDIMENTOEXT.CODCOLIGADA
                  AND HCLIENTEATENDIMENTO.CODLOCAL = HATENDIMENTOEXT.CODLOCAL
       LEFT JOIN GCOLIGADA (NOLOCK)
              ON GCOLIGADA.CODCOLIGADA = HATENDIMENTOEXT.CODCOLIGADA
       LEFT JOIN HTAREFA (NOLOCK)
              ON HTAREFA.CODCOLIGADA = HATENDIMENTOEXT.CODCOLIGADA
                 AND HTAREFA.CODTIPOATENDIMENTO = HATENDIMENTOEXT.CODTIPOATENDIMENTO
                 AND HTAREFA.CODTAREFA = HATENDIMENTOEXT.CODTAREFA
       INNER JOIN HTIPOATENDIMENTO (NOLOCK)
               ON HTIPOATENDIMENTO.CODCOLIGADA = HATENDIMENTOEXT.CODCOLIGADA
                  AND HTIPOATENDIMENTO.CODTIPOATENDIMENTO = HATENDIMENTOEXT.CODTIPOATENDIMENTO
       LEFT JOIN HATENDENTE (NOLOCK)
              ON HATENDENTE.CODATENDENTE = HATENDIMENTOEXT.CODATENDENTE
                 AND HATENDENTE.CODCOLIGADA = HATENDIMENTOEXT.CODCOLIGADA
       LEFT JOIN PPESSOA PP2 (NOLOCK)
              ON PP2.CODIGO = HATENDENTE.CODPESSOA
       LEFT JOIN HATENDENTE AS HA2 (NOLOCK)
              ON HA2.CODATENDENTE = HATENDIMENTOEXT.CODATENDENTERESP
                 AND HA2.CODCOLIGADA = HATENDIMENTOEXT.CODCOLIGADA
       LEFT JOIN PPESSOA PP3 (NOLOCK)
              ON PP3.CODIGO = HA2.CODPESSOA
       LEFT JOIN SHABILITACAOALUNO (NOLOCK)
              ON SHABILITACAOALUNO.CODCOLIGADA = HTIPOATENDIMENTO.CODCOLIGADA
                 AND SHABILITACAOALUNO.RA = HATENDIMENTOEXT.RAALUNO
       LEFT JOIN SHABILITACAOFILIAL (NOLOCK)
              ON SHABILITACAOALUNO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
                 AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SHABILITACAOFILIAL.IDHABILITACAOFILIAL
       LEFT JOIN SCURSO (NOLOCK)
              ON SHABILITACAOFILIAL.CODCOLIGADA = SCURSO.CODCOLIGADA
                 AND SHABILITACAOFILIAL.CODCURSO = SCURSO.CODCURSO
       INNER JOIN SCONTRATO (NOLOCK)
               ON HATENDIMENTOEXT.CODCOLIGADA = SCONTRATO.CODCOLIGADA
                  AND HATENDIMENTOEXT.RAALUNO = SCONTRATO.RA
       INNER JOIN STIPOCURSO (NOLOCK)
               ON STIPOCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
                  AND STIPOCURSO.CODTIPOCURSO = SHABILITACAOFILIAL.CODTIPOCURSO
       LEFT JOIN SMATRICPL (NOLOCK)
              ON SHABILITACAOALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
                 AND SHABILITACAOALUNO.RA = SMATRICPL.RA
       LEFT JOIN SPLETIVO (NOLOCK)
              ON SHABILITACAOALUNO.CODCOLIGADA = SPLETIVO.CODCOLIGADA
                 AND SMATRICPL.IDPERLET = SPLETIVO.IDPERLET
                 AND SMATRICPL.IDHABILITACAOFILIAL = SHABILITACAOALUNO.IDHABILITACAOFILIAL
WHERE  1 = 1
       AND HCLIENTEATENDIMENTO.CODCOLIGADA = 1
       AND HATENDIMENTOEXT.ABERTURA BETWEEN '2026-04-01' AND '2026-07-24'
       AND SPLETIVO.IDPERLET IS NOT NULL
       AND SPLETIVO.IDPERLET = (SELECT TOP 1 IDPERLET
                                FROM   SMATRICPL (NOLOCK)
                                WHERE  SMATRICPL.CODCOLIGADA = 1
                                       AND SMATRICPL.RA = SHABILITACAOALUNO.RA
                                ORDER  BY IDPERLET DESC) 
