-- Criado em 23/07/2026
-- Gera a quantidade de execuções de todos os relatórios/serviços de Declaração de Matrícula
SELECT  IDREL, 
        SUBSTRING(DESCRELAT,1,PATINDEX('%-%',DESCRELAT)-1) AS CODIGO,
        REPLACE(REPLACE(SUBSTRING(DESCRELAT,PATINDEX('%-%',DESCRELAT)+2,LEN(DESCRELAT) ),'.PDF',''),'.NONE','') AS NOME,
        YEAR(RECCREATEDON) ANO, 
        MONTH(RECCREATEDON) MES, 
        COUNT(*) AS QTD_GERACAO
FROM GRELBATCH
WHERE CODCOLIGADA = 1
AND CODSISTEMA = 'S'
/*
AND IDREL IN (  1177,1511,1127,
                1552,1558,1573,
                1491,1845,1614,
                814,1057,2090,
                1138)
AND YEAR(RECCREATEDON) = 2026
--AND DESCRELAT like '%DECLARAÇÃO DE MATRÍCULA%'
--and DESCRELAT like '%STRICTU%'
--AND MONTH(RECCREATEDON) = 7  
*/
GROUP BY    IDREL, 
            SUBSTRING(DESCRELAT,1,PATINDEX('%-%',DESCRELAT)-1),
            REPLACE(REPLACE(SUBSTRING(DESCRELAT,PATINDEX('%-%',DESCRELAT)+2,LEN(DESCRELAT) ),'.PDF',''),'.NONE',''),
            YEAR(RECCREATEDON), 
            MONTH(RECCREATEDON)
ORDER BY    SUBSTRING(DESCRELAT,1,PATINDEX('%-%',DESCRELAT)-1),
            REPLACE(REPLACE(SUBSTRING(DESCRELAT,PATINDEX('%-%',DESCRELAT)+2,LEN(DESCRELAT) ),'.PDF',''),'.NONE',''),
            YEAR(RECCREATEDON), 
            MONTH(RECCREATEDON) 


-- Query base
SELECT DESCRELAT, YEAR(RECCREATEDON) ANO, MONTH(RECCREATEDON) MES, COUNT(*)
FROM GRELBATCH
WHERE CODCOLIGADA = 1
AND CODSISTEMA = 'S'
AND IDREL IN (1511,1552)
--AND RECCREATEDBY = '10741479'
GROUP BY YEAR(RECCREATEDON), MONTH(RECCREATEDON), DESCRELAT
ORDER BY DESCRELAT, YEAR(RECCREATEDON), MONTH(RECCREATEDON)


-- RELATÓRIOS / DECLARAÇÃO DE MATRÍCULA
SELECT  CODCOLIGADA,
        CODAPLICACAO,
        ID,
        CODIGO,
        DESCRICAO,
        GUID,
        *
FROM RRPTREPORT
WHERE CODCOLIGADA = 1
AND DESCRICAO LIKE '%DECLARA%'
AND DESCRICAO LIKE '%MATRÍCULA%'

/* PARÂMETROS DE RELATÓRIOS DISPONIBILIZADOS NO EDUCACIONAL/PORTAL
        A tabela que armazena a informação é a SPARAM. 
        No campo MEMO ele retorna todos os códigos dos relatórios disponibilizados. 
        Para Relatórios de Professores o campo ID será 'RELGERADORPROFNET'; 
        para relatórios de Alunos o campo ID será 'RELGERADORALUNONET'. 
        No campo TEXTO ele traz um MEMO de todos os relatórios que já foram disponibilizados.
        Link: https://centraldeatendimento.totvs.com/hc/pt-br/articles/15024936775959-TOTVS-Educacional-Educacional-EDU-Tabela-que-armazena-os-Relat%C3%B3rios-informados-nos-Par%C3%A2metros-Educacionais-de-Portal
*/
SELECT MEMO
FROM SPARAM
WHERE ID = 'RELGERADORALUNONET'


-- LISTA OS RELATÓRIOS DE DECLARAÇÃO DE MATRÍCULA DE ACORDO COM O PARÂMETRO DO EDUCACIONAL/PORTAL
SELECT 
    R.CODAPLICACAO,
    R.CODCOLIGADA,
    P.CODFILIAL,
    P.CODTIPOCURSO,
    R.ID,
    R.CODIGO,
    R.GUID,
    R.DESCRICAO
FROM 
    RRPTREPORT R
    INNER JOIN 
        SPARAM P 
                ON P.MEMO LIKE '%' + CAST(R.Codigo AS NVARCHAR(MAX)) + '%'
WHERE (R.DESCRICAO LIKE '%DECLARA%'
AND R.DESCRICAO LIKE '%MATRÍCULA%')
ORDER BY        R.CODAPLICACAO,
                R.CODCOLIGADA,
                P.CODFILIAL,
                P.CODTIPOCURSO




SELECT  CODCOLIGADA,
        CODTIPOCURSO,
        CODFILIAL,
        MEMO
FROM SPARAM
WHERE ID = 'RELGERADORALUNONET'
AND MEMO LIKE ( SELECT CODIGO
                FROM RRPTREPORT
                WHERE CODCOLIGADA = 1
                AND DESCRICAO LIKE '%DECLARA%'
                AND DESCRICAO LIKE '%MATRÍCULA%')


LIKE '%001.02.02.20%'

SELECT  CODCOLIGADA,
        CODAPLICACAO,
        ID,
        CODIGO,
        DESCRICAO,
        GUID,
        *
FROM RRPTREPORT
WHERE CODCOLIGADA = 1
AND DESCRICAO LIKE '%DECLARA%'
AND DESCRICAO LIKE '%MATRÍCULA%'



SELECT *
FROM GDIC
WHERE TABELA LIKE 'S%'
AND COLUNA = '#'
AND DESCRICAO LIKE '%RELAT%'









SELECT *
FROM SZRELATCONFIG

SELECT *
FROM SPARAMRELAT




select top 10 *
from     RRPTREPORT
where id = 814
